daemon off
setup_mode off
log_level 6
log_type all
videodevice /dev/video2
v4l2_palette 17
input -1
norm 0
frequency 0
power_line_frequency -1
picture_output off
picture_output_motion off
movie_output off
stream_port 8081
stream_localhost off
stream_auth_method 0
; stream_authentication admin:secretpass123
webcontrol_port 8080
webcontrol_localhost off
