/**
 * Node-runtime mirror of src/lib/config.ts.
 *
 * The scripts (camera launcher, setup) run under plain Node and can't import
 * the app's TypeScript, so this file re-implements the same env-driven config.
 * Keep the two in sync — they intentionally share variable names and defaults.
 */

function env(name, fallback) {
  const v = process.env[name];
  return v === undefined || v === "" ? fallback : v;
}

export function readConfig() {
  const source = env("CAMERA_SOURCE", "mac");
  return {
    source,
    device: env("CAMERA_DEVICE", source === "linux" ? "/dev/video0" : "0"),
    resolution: env("CAMERA_RESOLUTION", "1280x720"),
    fps: env("CAMERA_FPS", "25"),
    ports: {
      app: Number(env("APP_PORT", "3000")),
      rtsp: Number(env("RTSP_PORT", "8554")),
      webrtc: Number(env("WEBRTC_PORT", "8889")),
      hls: Number(env("HLS_PORT", "8888")),
      // MediaMTX control API — bound to localhost only, used by the app to
      // report camera online/offline + uptime.
      api: Number(env("MEDIAMTX_API_PORT", "9997")),
    },
    streamName: env("STREAM_NAME", "cam"),
    // Comma-separated extra hosts advertised in WebRTC ICE candidates.
    // On Ubuntu behind Tailscale, set this to the machine's 100.x.x.x address.
    webrtcAdditionalHosts: env("WEBRTC_ADDITIONAL_HOSTS", ""),
    // Lockdown (default): bind every MediaMTX port to 127.0.0.1 so the raw
    // stream is NOT reachable off-box — the app proxies it behind auth. Set to
    // "false" to expose the WebRTC port on the tailnet for remote real-time.
    localhostOnly: env("MEDIAMTX_LOCALHOST_ONLY", "true").toLowerCase() !== "false",
  };
}

/** ffmpeg input argv for capturing the local camera on this OS. */
export function ffmpegInputArgs(cfg) {
  const { device, resolution, fps } = cfg;
  if (cfg.source === "linux") {
    return [
      "-f", "v4l2",
      "-framerate", fps,
      "-video_size", resolution,
      "-i", device,
    ];
  }
  // macOS AVFoundation. "<index>:none" = that video device, no audio.
  return [
    "-f", "avfoundation",
    "-framerate", fps,
    "-video_size", resolution,
    "-i", `${device}:none`,
  ];
}

export function rtspPublishUrl(cfg) {
  return `rtsp://localhost:${cfg.ports.rtsp}/${cfg.streamName}`;
}

/** Render a MediaMTX YAML config from our env-driven ports/stream. */
export function renderMediamtxConfig(cfg) {
  const extraHosts = cfg.webrtcAdditionalHosts
    .split(",")
    .map((h) => h.trim())
    .filter(Boolean);

  // In lockdown, HTTP-facing services bind to loopback only. RTSP (ffmpeg
  // publishes from localhost) and the API (app reads it from localhost) are
  // ALWAYS loopback. WebRTC can optionally listen on all interfaces so a
  // Tailscale viewer can get real-time media (its P2P leg can't be proxied).
  const lo = "127.0.0.1";
  const webrtcBind = cfg.localhostOnly ? lo : "";

  const lines = [
    "# AUTO-GENERATED by Camio (scripts/camera.mjs) — do not edit by hand.",
    "logLevel: info",
    "api: yes",
    `apiAddress: ${lo}:${cfg.ports.api}`,
    "metrics: no",
    "playback: no",
    "rtmp: no",
    "srt: no",
    "moq: no",
    "",
    "rtsp: yes",
    `rtspAddress: ${lo}:${cfg.ports.rtsp}`,
    "rtspTransports: [tcp]",
    "",
    "hls: yes",
    `hlsAddress: ${lo}:${cfg.ports.hls}`,
    "hlsVariant: mpegts",
    "hlsAlwaysRemux: yes",
    "",
    "webrtc: yes",
    `webrtcAddress: ${webrtcBind}:${cfg.ports.webrtc}`,
    "webrtcLocalUDPAddress: :8189",
  ];
  if (extraHosts.length) {
    lines.push(`webrtcAdditionalHosts: [${extraHosts.join(", ")}]`);
  }
  lines.push("", "paths:", `  ${cfg.streamName}:`, "    source: publisher", "");
  return lines.join("\n");
}
